# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
  # give any name to job
  4x-electron:
    # use Cypress built Docker image with Node 10 and npm 6
    docker:
      - image: cypress/base:10
    # tells CircleCI to execute this job on 4 machines simultaneously
    parallelism: 4
    steps:
      - checkout
      # note: omitting caching for brevity
      # quickly install NPM dependencies
      - npm ci
      # load balance all tests across 4 CI machines
      - $(npm bin)/cypress run --parallel
